//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAR1_Demo_exam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VAR1Entities : DbContext
    {
        public VAR1Entities()
            : base("name=VAR1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Firma> Firmas { get; set; }
        public virtual DbSet<Pol> Pols { get; set; }
        public virtual DbSet<Polzovatel> Polzovatels { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<Rol_Polz> Rol_Polz { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Zakaz> Zakazs { get; set; }
    }
}
