//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAR1_Demo_exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_Polz
    {
        public long ID_Polz { get; set; }
        public long ID_Rol { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
